[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npm run seed"

[deploy]
startCommand = "node dist/src/main"
healthcheckPath = "/api"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs_18"] 